scripts:
    - name: Set up code signing settings on Xcode project
      script: xcode-project use-profiles
    - name: Get Flutter dependencies
      script: flutter packages pub get
    - name: Flutter analyze
      script: flutter analyze
    - name: Flutter unit tests
      script: flutter test
    - name: Install pods
      script: find . -name "Podfile" -execdir pod install \;
    - name: Flutter build IPA
      script: flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
artifacts:
    - build/ios/ipa/*.ipa
