name: Build Flutter iOS App

on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]

jobs:
    build-ios:
        runs-on: macos-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: "3.32.5"
                  channel: "stable"

            - name: Install dependencies
              run: flutter pub get

            - name: Run tests (optional)
              run: flutter test

            - name: Build iOS (without signing)
              run: flutter build ios --release --no-codesign

            - name: Create IPA (Archive method)
              run: |
                  cd ios
                  xcodebuild -workspace Runner.xcworkspace \
                    -scheme Runner \
                    -configuration Release \
                    -destination 'generic/platform=iOS' \
                    -archivePath build/Runner.xcarchive \
                    archive
                  xcodebuild -exportArchive \
                    -archivePath build/Runner.xcarchive \
                    -exportPath build \
                    -exportOptionsPlist exportOptions.plist

            - name: Upload IPA artifact
              uses: actions/upload-artifact@v4
              with:
                  name: iOS-IPA
                  path: ios/build/*.ipa
                  retention-days: 30
